go:
    # Whenever the Go version is updated here and
    # .circle/config.yml should also be updated.
    version: 1.12
repository:
    path: github.com/superq/smokeping_prober
build:
    flags: -a -tags 'netgo static_build'
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}

tarball:
    files:
        - LICENSE
