go:
  # This must match .circle/config.yml.
  version: 1.14
repository:
  path: github.com/superq/smokeping_prober
build:
  flags: -mod=vendor -a -tags 'netgo static_build'
  ldflags: |
    -X github.com/prometheus/common/version.Version={{.Version}}
    -X github.com/prometheus/common/version.Revision={{.Revision}}
    -X github.com/prometheus/common/version.Branch={{.Branch}}
    -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}

tarball:
  files:
  - LICENSE
crossbuild:
  platforms:
  - darwin/amd64
  - dragonfly/amd64
  - freebsd/amd64
  - freebsd/arm
  - linux/amd64
  - linux/arm
  - linux/arm64
  - linux/mips64
  - linux/mips64le
  - linux/ppc64
  - linux/ppc64le
  - linux/s390x
  - netbsd/amd64
  - netbsd/arm
  - openbsd/amd64
  - openbsd/arm
  - windows/amd64
