---
version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.16.0

executors:
  # This must match .promu.yml.
  golang:
    docker:
    - image: cimg/go:1.18

jobs:
  test:
    executor: golang

    steps:
    - checkout
    - run: go mod download
    - run: make promu
    - run: make style lint unused test build
    - run: rm -v smokeping_prober

workflows:
  version: 2
  smokeping_prober:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - prometheus/build:
        name: build
        parallelism: 3
        promu_opts: "-p linux/amd64 -p windows/amd64 -p linux/arm64 -p darwin/amd64 -p darwin/arm64 -p linux/386"
        filters:
          tags:
            ignore: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
          branches:
            ignore: /^(master|release-.*|.*build-all.*)$/
    - prometheus/build:
        name: build_all
        parallelism: 3
        filters:
          branches:
            only: /^(master|release-.*|.*build-all.*)$/
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
    - prometheus/publish_master:
        docker_hub_organization: superque
        quay_io_organization: superq
        requires:
        - test
        - build_all
        filters:
          branches:
            only: master
    - prometheus/publish_release:
        docker_hub_organization: superque
        quay_io_organization: superq
        requires:
        - test
        - build_all
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
